### ISSUE TITLE
[BUG] sonar-scanner падает при загрузке файла в формате reportjson

### ISSUE THREAD

**Issue by ovcharenko-di** [otymko/acc-export#45]
Логов, к сожалению, не сохранилось.
НО после смены формата файла на genericissue анализ прошел успешно.

**Comment by foxxof06** [comment]
Не такая?

20:25:34  20:25:33.927 INFO: C:\Program Files (x86)\Jenkins\workspace\PIF3_CA\sonar_temp\acc.json
20:25:35  20:25:35.519 ERROR: Can't parse analysis report file
20:25:35  com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `java.nio.file.Path`, problem: Illegal character in path at index 18: file:///C:/Program Files (x86)/Jenkins/workspace/PIF3_CA/Repo/src/Ext/OrdinaryApplicationModule.bsl
20:25:35   at [Source: (StringReader); line: 5, column: 9] (through reference chain: com.github._1c_syntax.bsl.languageserver.reporters.data.AnalysisInfo["fileinfos"]->java.util.ArrayList[0]->com.github._1c_syntax.bsl.languageserver.reporters.data.FileInfo["path"])
20:25:35  	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
20:25:35  	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1758)
20:25:35  	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1128)
20:25:35  	at com.fasterxml.jackson.databind.ext.NioPathDeserializer.deserialize(NioPathDeserializer.java:66)
20:25:35  	at com.fasterxml.jackson.databind.ext.NioPathDeserializer.deserialize(NioPathDeserializer.java:23)
20:25:35  	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
20:25:35  	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:291)
20:25:35  	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:250)
20:25:35  	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
20:25:35  	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:542)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:535)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:419)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1322)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:331)
20:25:35  	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
20:25:35  	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
20:25:35  	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
20:25:35  	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3434)
20:25:35  	at com.github._1c_syntax.bsl.sonar.LanguageServerDiagnosticsLoaderSensor.getAnalysisInfo(LanguageServerDiagnosticsLoaderSensor.java:136)
20:25:35  	at com.github._1c_syntax.bsl.sonar.LanguageServerDiagnosticsLoaderSensor.parseAndSaveResults(LanguageServerDiagnosticsLoaderSensor.java:82)
20:25:35  	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
20:25:35  	at com.github._1c_syntax.bsl.sonar.LanguageServerDiagnosticsLoaderSensor.execute(LanguageServerDiagnosticsLoaderSensor.java:75)
20:25:35  	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
20:25:35  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
20:25:35  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
20:25:35  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
20:25:35  	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
20:25:35  	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
20:25:35  	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
20:25:35  	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
20:25:35  	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:388)
20:25:35  	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:384)
20:25:35  	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:353)
20:25:35  	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
20:25:35  	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
20:25:35  	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
20:25:35  	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
20:25:35  	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
20:25:35  	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
20:25:35  	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
20:25:35  	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
20:25:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
20:25:35  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
20:25:35  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:25:35  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
20:25:35  	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
20:25:35  	at com.sun.proxy.$Proxy0.execute(Unknown Source)
20:25:35  	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
20:25:35  	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
20:25:35  	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
20:25:35  	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
20:25:35  	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
20:25:35  Caused by: java.net.URISyntaxException: Illegal character in path at index 18: file:///C:/Program Files (x86)/Jenkins/workspace/PIF3_CA/Repo/src/Ext/OrdinaryApplicationModule.bsl
20:25:35  	at java.base/java.net.URI$Parser.fail(URI.java:2915)
20:25:35  	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
20:25:35  	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
20:25:35  	at java.base/java.net.URI$Parser.parse(URI.java:3116)
20:25:35  	at java.base/java.net.URI.<init>(URI.java:600)
20:25:35  	at com.fasterxml.jackson.databind.ext.NioPathDeserializer.deserialize(NioPathDeserializer.java:64)
20:25:35  	... 53 common frames omitted

**Comment by ovcharenko-di** [comment]
Вроде нет.

А данная ошибка указывает на вполне определенное место в конкретном файле. Что там, интересно?

**Comment by foxxof06** [comment]
> 
> 
> Вроде нет.
> 
> А данная ошибка указывает на вполне определенное место в конкретном файле. Что там, интересно?

С этой ошибкой разобрался. В одной из веток git (фиксики2) её исправили. Суть проблемы - пробелы в пути к файлу.

Падать может еще и по другой причине, у меня к примеру символы перевода строки при выгрузке конфигурации в файлы, были разными и при открытии текста какого-либо выгруженного модуля, в самой 1С и в стороннем редакторе давали разное количество строк и получалось что в json файле указатели были не на ту строку кода что требовалось. При загрузке таких данных Сонар Сканер падал. Решил это просто. В модуле обработки сделал так:

ТекстовыйДокумент.Прочитать(Файл.ПолноеИмя, КодировкаТекста.UTF8, Символы.ПС);

Изначально там было без параметра Символы.ПС
